"""Nginx configuration renderer for LL-HLS serving.

Generates a complete ``nginx.conf`` from a :class:`~config.NginxConfigParams`
instance.  The generated configuration:

* Proxies ALL requests to the Python LL-HLS server (upstream ``llhls``).
* Overrides ``Cache-Control`` and ``Content-Type`` for ``.ts`` segments
  (long-lived, immutable) and ``.m3u8`` playlists (no-cache).
* Sets ``proxy_read_timeout`` high enough to accommodate the LL-HLS
  blocking-playlist-reload mechanism (``_HLS_msn`` / ``_HLS_part`` params).
* Adds CORS headers so the web client's ``hls.js`` can fetch content
  cross-origin.
* Exposes a ``/health`` endpoint (no upstream, no logging) for container
  readiness checks.

Usage
-----
::

    from config import NginxConfigParams
    from generate_config import render, write

    params = NginxConfigParams()
    params.validate()
    conf = render(params)
    write(params, "/etc/nginx/nginx.conf")
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from config import NginxConfigParams


# ---------------------------------------------------------------------------
# Template
# ---------------------------------------------------------------------------

_TEMPLATE = """\
# Generated by edge/nginx/generate_config.py
# DO NOT EDIT manually — regenerate with: python generate_config.py

worker_processes  {worker_processes};

events {{
    worker_connections  {worker_connections};
}}

http {{
    include       mime.types;
    default_type  application/octet-stream;

    sendfile           on;
    keepalive_timeout  65;

    # Suppress Nginx version in error pages and Server header.
    server_tokens off;

    # -----------------------------------------------------------------------
    # Upstream: Python LL-HLS server (edge/video-streamer/hls/server.py)
    # -----------------------------------------------------------------------
    upstream llhls {{
        server {upstream_host}:{upstream_port};
        keepalive {keepalive_upstream};
    }}

    # -----------------------------------------------------------------------
    # HLS origin server
    # -----------------------------------------------------------------------
    server {{
        listen       {listen_port};
        server_name  _;

        # --- Readiness / liveness probe -----------------------------------
        location = /health {{
            access_log  off;
            return 200 "OK\\n";
            add_header  Content-Type text/plain;
        }}

        # --- MPEG-TS segment files (.ts) -----------------------------------
        # Segments are immutable once written; cache aggressively.
        location ~* \\.ts$ {{
            proxy_pass              http://llhls;
            proxy_http_version      1.1;
            proxy_set_header        Connection "";
            proxy_set_header        Host $host;

            # Strip upstream Cache-Control and set our own.
            proxy_hide_header       Cache-Control;
            add_header              Cache-Control "max-age={segment_cache_max_age}, public, immutable";

            # Explicit MIME type (some upstreams omit it).
            add_header              Content-Type "{mime_ts}";

            # CORS — required for hls.js running on a different origin.
            add_header              Access-Control-Allow-Origin  "{cors_origin}";
            add_header              Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
            add_header              Access-Control-Allow-Headers "Range";
            add_header              Access-Control-Expose-Headers "Content-Length, Content-Range";
        }}

        # --- HLS playlist files (.m3u8) ------------------------------------
        # Playlists must never be cached; clients refresh them continuously.
        # proxy_read_timeout must exceed the server-side blocking-reload
        # wait period (default 10 s in LLHLSServer) to avoid 504 responses.
        location ~* \\.m3u8$ {{
            proxy_pass              http://llhls;
            proxy_http_version      1.1;
            proxy_set_header        Connection "";
            proxy_set_header        Host $host;

            # LL-HLS blocking reload can hold the connection open; give it room.
            proxy_read_timeout      {playlist_proxy_timeout}s;

            # Forward response immediately; do not buffer playlist bytes.
            proxy_buffering         off;

            proxy_hide_header       Cache-Control;
            add_header              Cache-Control "no-cache, no-store, must-revalidate";
            add_header              Pragma "no-cache";
            add_header              Expires "0";

            add_header              Content-Type "{mime_m3u8}";

            add_header              Access-Control-Allow-Origin  "{cors_origin}";
            add_header              Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
            add_header              Access-Control-Allow-Headers "Range";
        }}

        # --- Everything else (master playlist at /, OPTIONS pre-flight) ----
        location / {{
            proxy_pass              http://llhls;
            proxy_http_version      1.1;
            proxy_set_header        Connection "";
            proxy_set_header        Host $host;

            proxy_read_timeout      {playlist_proxy_timeout}s;
            proxy_buffering         off;

            add_header              Access-Control-Allow-Origin  "{cors_origin}";
            add_header              Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
            add_header              Access-Control-Allow-Headers "Range";

            # Handle CORS pre-flight without touching the upstream.
            if ($request_method = OPTIONS) {{
                add_header          Access-Control-Allow-Origin  "{cors_origin}";
                add_header          Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
                add_header          Access-Control-Allow-Headers "Range";
                add_header          Access-Control-Max-Age 86400;
                return 204;
            }}
        }}
    }}
}}
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render(params: NginxConfigParams) -> str:
    """Render a complete ``nginx.conf`` string from *params*.

    Parameters
    ----------
    params:
        Validated :class:`~config.NginxConfigParams` instance.

    Returns
    -------
    str
        Full ``nginx.conf`` content, ready to write to disk.
    """
    from config import MIME_M3U8, MIME_TS

    return _TEMPLATE.format(
        worker_processes=params.worker_processes,
        worker_connections=params.worker_connections,
        upstream_host=params.upstream_host,
        upstream_port=params.upstream_port,
        keepalive_upstream=params.keepalive_upstream,
        listen_port=params.listen_port,
        segment_cache_max_age=params.segment_cache_max_age,
        playlist_proxy_timeout=params.playlist_proxy_timeout,
        cors_origin=params.cors_origin,
        mime_ts=MIME_TS,
        mime_m3u8=MIME_M3U8,
    )


def write(params: NginxConfigParams, dest: str | Path = "nginx.conf") -> Path:
    """Render and write ``nginx.conf`` to *dest*.

    Parameters
    ----------
    params:
        Validated :class:`~config.NginxConfigParams` instance.
    dest:
        Destination file path (default: ``nginx.conf`` in the current directory).

    Returns
    -------
    Path
        Resolved path of the written file.
    """
    path = Path(dest).resolve()
    path.write_text(render(params), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    import argparse
    import sys

    from config import load_from_env

    parser = argparse.ArgumentParser(
        description="Generate nginx.conf for LL-HLS serving from environment variables."
    )
    parser.add_argument(
        "--output",
        "-o",
        default="-",
        help="Output file path (default: stdout)",
    )
    args = parser.parse_args()

    params = load_from_env()
    try:
        params.validate()
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    conf = render(params)

    if args.output == "-":
        print(conf, end="")
    else:
        out_path = write(params, args.output)
        print(f"Written to {out_path}", file=sys.stderr)
