#!/usr/bin/env bash
# Write edge/monitoring/system-metrics.env on the Raspberry Pi from secrets.
#
# Used by `make deploy-edge` (local + GitHub Actions). Requires:
#   PI_DEVICE_TOKEN   — per-device token (GitHub secret / local env)
#   GCP_PROJECT_ID    — used to build the unifiedIngress URL
# Optional:
#   PI_RPI_DEVICE_ID  — defaults to rpi-camera-01
#
# Remote write also needs the usual PI_IP / PI_USER / PI_SSH_PORT / PI_REMOTE_PATH.
#
# Usage:
#   bash edge/scripts/write-pi-telemetry-env.sh --remote
#   bash edge/scripts/write-pi-telemetry-env.sh --stdout   # for tests / inspection
#
# Never prints the token value except into the remote file / --stdout content.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EDGE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

MODE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --remote) MODE="remote"; shift ;;
    --stdout) MODE="stdout"; shift ;;
    -h|--help)
      sed -n '2,20p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

if [[ -z "${MODE}" ]]; then
  echo "Usage: $0 --remote | --stdout" >&2
  exit 2
fi

PI_DEVICE_TOKEN="${PI_DEVICE_TOKEN:-}"
GCP_PROJECT_ID="${GCP_PROJECT_ID:-}"
PI_RPI_DEVICE_ID="${PI_RPI_DEVICE_ID:-rpi-camera-01}"

if [[ -z "${PI_DEVICE_TOKEN}" ]]; then
  echo "ERROR: PI_DEVICE_TOKEN is not set — cannot write system-metrics.env" >&2
  echo "  Generate a token with: bash cloud/functions/setup-device-tokens.sh --device-id rpi-camera-01" >&2
  echo "  then set the PI_DEVICE_TOKEN GitHub Actions secret (or export it locally)." >&2
  exit 1
fi

if [[ -z "${GCP_PROJECT_ID}" ]]; then
  echo "ERROR: GCP_PROJECT_ID is not set — cannot derive TELEMETRY_ENDPOINT" >&2
  exit 1
fi

TELEMETRY_ENDPOINT="https://europe-central2-${GCP_PROJECT_ID}.cloudfunctions.net/unifiedIngress"

# Build file contents. Values are written as KEY=VALUE with no shell metachar
# expansion on the Pi side (consumers parse assignment-only).
# Escape nothing special beyond ensuring we don't embed raw newlines in values.
if [[ "${PI_DEVICE_TOKEN}" == *$'\n'* ]] || [[ "${PI_RPI_DEVICE_ID}" == *$'\n'* ]]; then
  echo "ERROR: secret/device id must not contain newlines" >&2
  exit 1
fi

ENV_CONTENTS="$(cat <<EOF
# Auto-generated by edge/scripts/write-pi-telemetry-env.sh — do not edit.
# Shared by system_metrics_collector and video-streamer (via start-all / systemd).
TELEMETRY_ENDPOINT=${TELEMETRY_ENDPOINT}
TELEMETRY_DEVICE_TOKEN=${PI_DEVICE_TOKEN}
RPI_DEVICE_ID=${PI_RPI_DEVICE_ID}
EOF
)"

if [[ "${MODE}" == "stdout" ]]; then
  printf '%s\n' "${ENV_CONTENTS}"
  exit 0
fi

# --remote
PI_IP="${PI_IP:-}"
PI_USER="${PI_USER:-pi}"
PI_SSH_PORT="${PI_SSH_PORT:-22}"
PI_REMOTE_PATH="${PI_REMOTE_PATH:-/home/pi/robot/edge/}"

if [[ -z "${PI_IP}" ]]; then
  echo "ERROR: PI_IP is not set — cannot write env file on the Pi" >&2
  exit 1
fi

# Normalize trailing slash for path join.
REMOTE_EDGE="${PI_REMOTE_PATH%/}"
REMOTE_ENV="${REMOTE_EDGE}/monitoring/system-metrics.env"
REMOTE_DIR="${REMOTE_EDGE}/monitoring"

echo "==> Writing ${REMOTE_ENV} on ${PI_USER}@${PI_IP} (endpoint derived from GCP_PROJECT_ID=${GCP_PROJECT_ID})"

# Pipe contents over SSH; write atomically (temp + mv) and chmod 600.
# Use a remote path under /tmp with mktemp so we never leave a world-readable
# partial file next to the final destination.
printf '%s\n' "${ENV_CONTENTS}" | ssh \
  -p "${PI_SSH_PORT}" \
  -o StrictHostKeyChecking=accept-new \
  -o BatchMode=yes \
  "${PI_USER}@${PI_IP}" \
  "set -euo pipefail
   mkdir -p '${REMOTE_DIR}'
   tmp=\$(mktemp '${REMOTE_DIR}/.system-metrics.env.XXXXXX')
   trap 'rm -f \"\$tmp\"' EXIT
   cat > \"\$tmp\"
   chmod 600 \"\$tmp\"
   mv \"\$tmp\" '${REMOTE_ENV}'
   trap - EXIT
   echo \"Wrote ${REMOTE_ENV} (mode 600)\""

echo "==> Pi telemetry env file ready."
